"""complete_consumer_profiles_table

Revision ID: 95ea6c3411df
Revises: c4d8e9f0a1b3
Create Date: 2026-03-29 13:18:39.446833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ea6c3411df'
down_revision: Union[str, None] = 'c4d8e9f0a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_profiles', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('consumer_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('consumer_profiles', 'home_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    op.alter_column('consumer_profiles', 'home_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    op.alter_column('consumer_profiles', 'work_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    op.alter_column('consumer_profiles', 'work_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    op.create_index(op.f('ix_consumer_profiles_push_subscribed'), 'consumer_profiles', ['push_subscribed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumer_profiles_push_subscribed'), table_name='consumer_profiles')
    op.alter_column('consumer_profiles', 'work_lng',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('consumer_profiles', 'work_lat',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('consumer_profiles', 'home_lng',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('consumer_profiles', 'home_lat',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('consumer_profiles', 'updated_at')
    op.drop_column('consumer_profiles', 'created_at')
    # ### end Alembic commands ###
